name: "Close Stale Issues"
description: "Close issues with no recent activity"
author: "GitHub"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days."
          days-before-issue-stale: 30
          days-before-issue-close: 5
